pod_network_cidr: "192.168.0.0/16"
helm_keyring_url: "https://packages.buildkite.com/helm-linux/helm-debian/gpgkey"
helm_repo_url: "https://packages.buildkite.com/helm-linux/helm-debian/any/"
calico_yaml_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml"
cilium_helm_repo: "https://helm.cilium.io/"
cilium_version: "1.16.0"
cni_provider: "cilium" #values can be calico or cilium
ngnix_gateway_crds_url: "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml"
nginx_gateway_helm_url: "oci://ghcr.io/nginx/charts/nginx-gateway-fabric"